spring:
  thymeleaf:
    prefix: classpath:/static/

Encrypt:
  key: ${ENCRYPT_KEY}
  algo: ${ENCRYPT_ALGO}

oauth:
  apple:
    appleKeyId: ${APPLE_KEY_ID}
    appleTeamId: ${APPLE_TEAM_ID}
    appleBundleId: ${APPLE_BUNDLE_ID}
    classpath: ${APPLE_KEY_CLASSPATH}

server:
  ssl:
    key-store: /ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}