spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_ENDPOINT}/payrit_prod?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false

jwt:
  token:
    secret: ${JWT_SECRET}