package com.owl.payrit.domain.notification.entity;

public enum NotificationType {
    WELCOME,
    ID_VERIFICATION,
    APPROVAL_REQUEST,
    AFTER_APPROVAL_REQUEST,
    MODIFY_REQUEST,
    MODIFICATION_COMPLETE,
    PAYMENT_REQUIRED,
    PAYMENT_TIMEOUT,
    PAYMENT_COMPLETE,
    REPAYMENT_DUE,
    FULL_REPAYMENT_RECEIVED,
    FULL_REPAYMENT_MADE,
    PARTIAL_REPAYMENT,
    PARTIAL_REPAYMENT_CANCELLED,
    UNPAID,
}