name: payrit CI/CD Pipeline

on:
  push:
    branches: ["dev", "deploy-test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }} .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
    
      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          script: |
            if sudo docker ps -a | grep -q ${{ secrets.PROJECT_NAME }}; then
              sudo docker kill ${{ secrets.PROJECT_NAME }}
              sudo docker rm -f ${{ secrets.PROJECT_NAME }}
            fi
            if sudo docker images | grep -q "${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}"; then
              sudo docker rmi ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}
            fi
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}
            docker-compose up -d \
              -e SPRING_DATASOURCE_URL=jdbc:mariadb://${{ secrets.MARIADB_ENDPOINT }}/payrit_prod?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.MARIADB_USER }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MARIADB_PASSWORD }} \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

