name: payrit CI/CD Pipeline

on:
  push:
    branches: ["dev", "deploy-test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      - name: Create secret-key file
        run: |
          echo '${{ secrets.APPLE_SECRET_KEY }}' > src/main/resources/apple/AuthKey_32NZF755K3.p8
#          echo '${{ secrets.SSH_SECRET_KEY }}' | base64 --decode -i > src/main/resources/keystore.p12
#
      - name: List files in resources folder
        run: |
          ls src/main/resources/apple
          cat src/main/resources/apple/AuthKey_32NZF755K3.p8
          ls src/main/resources/

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }} .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}

      # key 파일을 복사하여 Dockerfile에서 해당 위치로 포함
      - name: Copy key file to Docker image
        run: |
          docker create --name temp-container ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}
          docker cp src/main/resources/apple/AuthKey_32NZF755K3.p8 temp-container:/app/src/main/resources/apple/AuthKey_32NZF755K3.p8
          docker commit temp-container ${{ secrets.DOCKERHUB_USERTAG }}/${{ secrets.PROJECT_NAME }}
          docker rm temp-container
    
      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          script: |
            ./scripts/deploy.sh

